server:
  port: 8080
  address: 0.0.0.0

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://tftshare.com:8080/api/oauth2/callback

  datasource:
    url: jdbc:mysql://tft-share-db.cvoms202yzka.ap-northeast-2.rds.amazonaws.com:3306/tft_share_db?useSSL=false&requireSSL=false&serverTimezone=Asia/Seoul

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

aws:
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
  s3:
    bucket-name: tft-share-bucket
    region: ap-northeast-2

# 운영 환경 프론트엔드 URL
frontend:
  url: https://tftshare.com
  login-success-path: /oauth2/callback

