server:
  port: 8080
  # 로컬 개발용
  address: localhost
  # 배포용
  # address: 0.0.0.0

spring:
  profiles:
    active: ${ENVIRONMENT:dev}  # 기본값은 개발 환경

  application:
    name: tft-share

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile
              - youtube.upload
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2000MB

# 공통 설정 (환경에 관계없이 동일한 설정)
jwt:
  secret: ${JWT_SECRET}

riot:
  api:
    key: ${RIOT_API_KEY}
    kr-url: https://kr.api.riotgames.com
    asia-url: https://asia.api.riotgames.com
