server:
  port: 8080
  address: localhost

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/api/oauth2/callback

  datasource:
    url: jdbc:mysql://localhost:3306/tft_share?useSSL=false&requireSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

aws:
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
  s3:
    bucket-name: tft-share-bucket
    region: ap-northeast-2

# 개발 환경 프론트엔드 URL
frontend:
  url: http://localhost:5173
  login-success-path: /login-success

